OnlineBanking/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using OnlineBanking.DataAccessLayer;
using OnlineBanking.Models;
using OnlineBanking.Services;
using OnlineBanking.Utilities;
using System.Data;

namespace OnlineBanking.Controllers
{

    


    [AuthenticationAdmin]
    public class AdminController : Controller
    {
        private readonly AdminService adminService;
        private static long _adminId { get; set; }

        public AdminController(AdminService _adminService)
        {
            adminService = _adminService;
        }
        [HttpGet]
        public IActionResult Home(Dictionary<string,string>? UserDetail)
        {
            if(UserDetail.ContainsKey("LoggerId")) {
                _adminId = Convert.ToInt64(UserDetail["LoggerId"]);
                HttpContext.Response.Redirect("/Admin/Home");
            }
            UserDetail user = adminService.GetAdminDetailsById(_adminId);
            return View(user);
        }
        [HttpGet]
        public IActionResult CustomerDetails()
        {
            List<Customer> list = adminService.GetCustomers();
            return View(list);  
        }
        [HttpGet]
        public IActionResult CreateUpdateCustomer(long id, string? accountNumber) 
        {
            if(id is 0)
            {
                if (accountNumber == null) return View("Create");
                Customer customer = new Customer();
                customer.AccountNumber = accountNumber;
                return View(customer);
            }
            else
            {
                Customer customer = adminService.GetCustomerById(id);
                return View(customer);
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateUpdateCustomer(Customer customer)
        {
            if (ModelState.IsValid)
            {
                bool res = adminService.CreateUpdateCustomer(customer);
                if (res)
                {
                    return RedirectToAction("CustomerDetails");
                }
            }
            return View(customer);
        }
        [HttpGet]
        public IActionResult DeleteCustomer(int id)
        {
            Customer customer = adminService.GetCustomerById(id);
            return View(customer);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteCustomer(Customer customer)
        {
            bool res = adminService.DeleteCustomer(customer.CustomerId);
            if(res)
            {
                return RedirectToAction("CustomerDetails");
            }
            return View(customer);
        }

        [HttpGet]
        public IActionResult TransactionHistory()
        {
            List<TransactionModel> list = adminService.GetTransactions();
            return View(list);
        }








        public bool IsInserted { get; private set; }
        [HttpGet]
        public IActionResult Accounts()
        {
            var accountModels = adminService.GetAllAccountList();
            if (accountModels.Count == 0)
            {
                TempData["InfoMessage"] = "Data not Availbe in Database.";
            }

            return View(accountModels);
        }

        // GET: AccountController/Details/5
        public ActionResult Detail(int id)
        {
            return View();
        }

        // GET: AccountController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AccountController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AccountModel accountModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    bool isInserted = adminService.InsertAccountModel(accountModel);

                    if (isInserted)
                    {
                        TempData["SuccessMessage"] = "Account Details is Saved";
                    }
                    else
                    {
                        TempData["ErrorMessage"] = "Account Details Not Saved";
                    }

                    return RedirectToAction("CreateUpdateCustomer",new { AccountNumber = accountModel.AccountNumber });
                }
                else
                {
                    // If the model state is invalid, add error messages to TempData
                    foreach (var key in ModelState.Keys)
                    {
                        if (ModelState[key].Errors.Count > 0)
                        {
                            TempData["ErrorMessage"] = ModelState[key].Errors[0].ErrorMessage;
                            break;
                        }
                    }

                    return View(accountModel);
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "An error occurred while saving the account details";
                return View(accountModel);
            }
        }

        // GET: AccountController/Edit/5
        public ActionResult Edit(int id)
        {
            var AccountModel = adminService.AccountId(id).FirstOrDefault();
            if (AccountModel == null)
            {
                TempData["InfoMessage"] = "Account is Not Available with ID" + id.ToString();
                return RedirectToAction("Home");
            }
            return View(AccountModel);
        }

        // POST: AccountController/Edit/5
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AccountModel accountModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    adminService.UpdateAccountModel(accountModel);
                }
                return RedirectToAction("Home");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return View();
            }
        }


        // GET: AccountController/Delete/5

        [HttpGet]
        public IActionResult Delete(string id)
        {
            adminService.DeleteAccount(id);
            return RedirectToAction("Home");
        }










    }
}

OnlineBanking/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using OnlineBanking.Models;
using OnlineBanking.Services;
using OnlineBanking.Utilities;
using System.Text.Json;

namespace OnlineBanking.Controllers
{
    [AuthenticationCustomer]
    public class CustomerController: Controller
    {
        private readonly CustomerService _customerService;
        private static long _customerId { get; set; }

        public CustomerController(CustomerService customerService)
        {
            _customerService = customerService;
        }

        [HttpGet]
        public IActionResult Home(Dictionary<string,string>? UserDetails)
        {
            if (UserDetails.ContainsKey("LoggerId"))
            {
                _customerId = Convert.ToInt64(UserDetails["LoggerId"]);
                HttpContext.Response.Redirect("/Customer/Home");
            }

            ViewBag.LoggerId = _customerId.ToString();
            UserDetail user = _customerService.GetCustomerDetailsById(_customerId);
            return View(user);
        }


        [HttpGet]
        public IActionResult CustomerTransactionsById()
        {
            List<TransactionModel> transaction = _customerService.CustomerTransactionsById(_customerId);
            return View(transaction);
        }
        [HttpGet]
        public IActionResult CreateTransaction()
        {
            AccountTransaction accountTransaction = new AccountTransaction();
            accountTransaction.AccountBalance = _customerService.GetAccountNumberWithAmount(_customerId);
            foreach(var item in accountTransaction.AccountBalance)
            {
                accountTransaction.accounts.Add(new SelectListItem()
                {
                    Text = item.Key,
                    Value = item.Key 
                });
            }
            accountTransaction.transactionModel.CustomerId = _customerId;
            return View(accountTransaction);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateTransaction(AccountTransaction accountTransaction,string CurrentBalance, string accountlist)
        {
            List<SelectListItem> CustomerAccounts = JsonSerializer.Deserialize<List<SelectListItem>>(accountlist);
            if(accountTransaction.transactionModel.TransferAmount > Convert.ToDecimal(CurrentBalance))
            {
                ModelState.AddModelError("transactionModel.TransferAmount", "Transfer amount is bigger than current balance");
                return View(accountTransaction);
            }
            if (ModelState.IsValid)
            {
                bool res = _customerService.CreateTransaction(accountTransaction.transactionModel);
                if (res)
                {
                    return RedirectToAction("CustomerTransactionsById");
                }
            }
            accountTransaction.accounts = CustomerAccounts;
            return View(accountTransaction);
        }

        [HttpPost]
        public IActionResult AccountBalanceInfo(Dictionary<string,string> model,  string selectedOption)
        {
            return Ok(model[selectedOption]);
        }
    }
}

OnlineBanking/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Online Bank</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">

    <link rel="stylesheet" href="~/css/codepen.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg box-shadow mb-3 navbar-dark bg-dark">
            <div class="container-fluid">
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="Home">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="CustomerDetails">Customer Details</a>
                        </li>

                        <li class="nav-item">
                             <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="Accounts">Account Details</a> 
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="TransactionHistory">Transaction History</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

OnlineBanking/Views/Shared/_CustomerLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>OnlineBank</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg box-shadow mb-3 navbar-dark bg-dark">
            <div class="container-fluid">
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Customer" asp-action="Home">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Customer" asp-action="CustomerTransactionsById">Transaction History</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Customer" asp-action="CreateTransaction">Transaction</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery//1.12.4/jquery.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

OnlineBanking/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Online Bank</title>
     <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
     <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/Loign.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@48,600,0,0" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" />
</head>



<body>
    @RenderBody()

    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery//1.12.4/jquery.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>